### PR TITLE
Use `expressive-code-twoslash` plugin

### PR DESCRIPTION
**Pull request by lishaduck**
## Type

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

`effective-code-twoslash` is a more featureful fork[^1] of the handrolled twoslash plugin included in the site.
The important part is that it has much nicer tooltips, where the types are syntax highlighted instead of all being purple.

[^1]: I skimmed the code and it looked similar, and it listed the site as inspiration in the credits.

## Related

- Related Issue #
- Closes #

### CODE REVIEW

**Comment by gcanti** [comment]
Nice! 

/cc @Adammatthiesen

**Comment by IMax153** [comment]
Indeed! Super cool work @Adammatthiesen

**Comment by IMax153** [comment]
Thanks @lishaduck 👍

**Comment by Adammatthiesen** [comment]
> Indeed! Super cool work @Adammatthiesen

Awesome to see you guys using it... I've been working for quite a while trying to figure out some of the nitty-gritty with this system, and even including minified floating_ui for the fancy popups... been talking to the creator of Expressive-code about some of the functionality for awhile as well!

**Pull request merged**
