### PR TITLE
Add Cookbook page

### PR DESCRIPTION
**Pull request by datner**
I'm on the fence if this should exist or not, but it could be a good place to see how people use effect and help people build intuitions

### CODE REVIEW

**Comment by aniravi24** [comment]
I don't think this should live inside the docs - I suspect it will get messy and hard to maintain really fast, given the size of the ecosystem of libraries growing, and the feature sets of these libraries.

I'm not sure the best way to maintain or organize something like this, but I'd probably put it in a separate repo.

**Comment by datner** [comment]
@aniravi24 
I generally agree, but as a community member said:

> It still might be useful for some random things. There is a good snippet here for using effect/schema with zod libs, for example, that I know I'm going to have to spend 20min searching for again at some point in the future.

So I made this PR and delegated the decision on the matter to the powers at be lol

**Comment by mikearnaldi** [comment]
I am mixed, I do think this type of content has a place in the website but not in a prominent manner, probably a section "Advanced & Crazy Usage" something targeting the curious

**Comment by datner** [comment]
@mikearnaldi So what's our next step?

**Comment by datner** [comment]
bump

**Pull request closed without merging**
