### PR TITLE
Twoslash Rich renderer

### PR DESCRIPTION
**Pull request by lishaduck**
## Type

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Makes the minimal changes to use the twoslash rich renderer.

Diff: <https://github.com/lishaduck/Effect-TS-website/compare/shiki-once-more...twoslash-rich>

## Related

- Related Issue #710
- Depends on #770

### CODE REVIEW

**Comment by mikearnaldi** [comment]
Looks like this has build issues, not sure if it's too slow or else

**Comment by lishaduck** [comment]
> Looks like this has build issues, not sure if it's too slow or else

Yeah, I'm not sure either. It build fine on my machine.

**Comment by lishaduck** [comment]
Ok, went ahead and pushed another commit so CI can rerun.

**Comment by lishaduck** [comment]
Closing as this is an essential part of #770, they sadly can't be separated.

**Pull request closed without merging**
