### PR TITLE
fix bun run directory

### PR DESCRIPTION
**Pull request by nisalVD**
## Type

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [x] Documentation Update

## Related

- Related Issue #133

### CODE REVIEW

**Comment by gcanti** [comment]
Thanks @nisalVD however I think the issue is the opposite, what needs to be corrected is:

```diff
-filename="src/index.ts"
+filename="index.ts"
```

since `bun init` outputs the following files (no `src` directory):

```
README.md bun.lockb index.ts  node_modules  package.json  tsconfig.json
```

**Comment by nisalVD** [comment]
please have a look now, i removed section of adding src/index.ts in the bun docs

**Comment by gcanti** [comment]
It appears you edited the Node.js tab (which is ok). I was referring to line 163 (included in the Bun tab instead) of the original MDX file.

**Comment by nisalVD** [comment]
sorry, fixed it now

**Pull request merged**
