### PR TITLE
Remove usage of `EffectAdapter`

### PR DESCRIPTION
**Pull request by fubhy**

### CODE REVIEW

**Comment by fubhy** [comment]
@mikearnaldi should we merge this yet or wait for it to prove itself in the wild first?

**Comment by mikearnaldi** [comment]
Let's go ahead and merge, I am now confident enough that TS 5.5 will have the fix

**Comment by riwsky** [comment]
@mikearnaldi what's the fix in question here? Is adapterless Effect.gen use somehow incorrect on TS versions <4.5?

**Comment by fubhy** [comment]
> @mikearnaldi what's the fix in question here? Is adapterless Effect.gen use somehow incorrect on TS versions <4.5?

There was a bug in TypeScript v5.4 and below that was fixed in TypeScript v5.5. It used to lead to type inference issues in some scenarios.

**Comment by riwsky** [comment]
How would the bug manifest—rejecting acceptable programs? or allowing unacceptable programs? I'm using adapterless .gen in a 5.4 codebase right now, and not hitting errors.

Is the issue in question https://github.com/microsoft/TypeScript/issues/57690 ?

**Comment by mikearnaldi** [comment]
The bug was: https://github.com/microsoft/TypeScript/pull/58337

**Comment by riwsky** [comment]
@mikearnaldi word. thanks!

**Pull request merged**
