### PR TITLE
feat: migrated docs from @effect/data

### PR DESCRIPTION
**Pull request by jessekelly881**
Migrated docs from @effect/data and added Mermaid rendering. Unfortunately I had to use a react component for mermaid rendering. I tried several using remark plugins for mermaid with no success. :(

### CODE REVIEW

**Review by IMax153 — CHANGES_REQUESTED** [review]
Thanks @jessekelly881 ! A few minor comments:

1. Can we make the capitalization here consistent? Also `Algebraic operations` should probably not be nested.

image

2. I think we are missing some peer deps. Specifically `mermaid` is causing an error for me.

image

**Comment by jessekelly881** [comment]
Fixed the dep. issue. Actually, I also got mermaid rendering to work without using an inline component as well. What's the issue with capitalization though? It looks correct to me.

**Comment by IMax153** [comment]
> What's the issue with capitalization though? It looks correct to me.

It's just a nitpick really - I'd like everything in headings to be in [title case](https://en.wikipedia.org/wiki/Title_case) but I can always go back and do a pass to fix all this later on.

Will pull down your changes and test locally soon 👍 Thanks for addressing!

**Comment by jessekelly881** [comment]
Oh! Now I understand! I thought you meant consistency in what word was capitalized. jaja. I'll update them.

**Comment by IMax153** [comment]
Just pulled the changes and tested. They look good to me. Once you've finished modifying the titles ping me again and I'll approve / run CI / merge.

**Comment by steida** [comment]
https://title.sh/ FTW

**Comment by jessekelly881** [comment]
Thanks @steida that site came in useful. @IMax153 updated.

**Comment by IMax153** [comment]
@jessekelly881 - looks like there are some `pre-commit` hooks failing. I'd suggest installing the hooks in your project locally with:

```bash
pre-commit install
```

Note that this assumes you have `pre-commit` installed on your machine.

Once installed, you can run the hooks manually with:

```bash
pre-commit run --all-files
```

**Comment by jessekelly881** [comment]
Yeah? I'll take a look. Btw, in general, having pre-commit hooks that ship with a project is generally a bad idea. It's much better to run tests as part of ci/cd(e.g. as part of GitHub workflows)

**Comment by IMax153** [comment]
> Btw, in general, having pre-commit hooks that ship with a project is a bad idea. It's much better to run tests as part of ci/cd(e.g. as part of GitHub workflows)

@jessekelly881 - I disagree with this sentiment entirely. The entire point of `pre-commit` hooks is to enforce code style / formatting / etc. Having them run on commit when a developer is working is the entire point.

We also have a CI-CD step in our GitHub actions that runs our `pre-commit` steps to check that everything is conformant to the rules we've specified and to catch situations such as this.

Furthermore, if a developer working on our projects has a full `nix` / `direnv` setup then the `pre-commit` hooks are setup automatically as part of the `nix` dev shell.

**Comment by jessekelly881** [comment]
Yeah, I understand the rational. I've used them for exactly this reason in the past. The problem is that it's a bit too invasive to a developers local "flow". It effects my local version of the project. If I want to create badly formatted unworking commits in my local(or commit on every key press) and then run git rebase -i once I actually want to submit that change. Those checks shouldn't be prescribed by the project. The only thing that's relevant from the remotes point of view is the final pr.

**Comment by IMax153** [comment]
You can just `--skip-verify` if you want to commit without running hooks.

**Comment by jessekelly881** [comment]
You can.. but that's not quite the point. Also, in some editors like vscode the UI commit will fail and as far as I have discovered there isn't any way around it. You have to drop into a terminal. Also, they just aren't very useful in my opinion.. especially for projects with multiple contributors. You can't rely on the user to run them so you have to run the tests on the remote anyway.

**Comment by IMax153** [comment]
I think we can agree to disagree :). @mikearnaldi and I have made the decision to use `pre-commit` to enforce consistent style and formatting _precisely because_ these are projects with multiple contributors.

**Comment by jessekelly881** [comment]
Jajaja. That's fine. :) It's a very minor thing anyway. It's opt in on your local machine anyway. Any reason you guys went with pre-commit instead of husky btw?

**Comment by IMax153** [comment]
> Any reason you guys went with pre-commit instead of husky btw?

We've used `husky` in the past but didn't like it much.

**Comment by jessekelly881** [comment]
Yeah? Also, totally bias video supporting my point jajaja. https://youtu.be/RAelLqnnOp0

**Comment by IMax153** [comment]
We didn't have issues, we just prefer using pre-commit. I'm sure I could find an equally compelling video touting the benefits of `pre-commit`. Also, I generally don't take advice from influencers as I prefer to formulate my own opinions about tooling through experience.

The point is given that Mike and I are maintainers of the project, we've decided to use this tool to help enforce formatting and styling to help make our lives a bit easier. We like this tool so we chose to use it. Does that mean we are married to this tool? No. May we choose to remove it in the future? Yes, just like we removed `husky`. But for now it stays.

I apologize if it is an inconvenience to your local workflow.

**Comment by IMax153** [comment]
Hey @jessekelly881 - just wanted to let you know I made a few minor commits to get this PR over the finish line. We appreciate your contribution very much! Thank you very much for your work getting these docs ported into the website!

**Review by IMax153 — APPROVED** [review]

**Comment by jessekelly881** [comment]
Thanks @IMax153. I normally would have fixed it sooner but I've been pretty under the weather for the last week. :( I'm glad we could get these docs into the website.

**Pull request merged**
