### PR TITLE
Shiki once more

### LINKED ISSUE #710: Upgrade Shiki
I've been looking into twoslash, and was curious how y'all had set it up. As I was looking, I noticed that y'all are still using Shikiji, which has been merged back into Shiki.
I'd be willing to try to upgrade it if that's something y'all are interested in.

`remark-shiki-twoslash` is deprecated as well (which is how I noticed it).

P.S. This is blank issue because that was an option, and the others seemed like they were for the project, not the website. I'm not ignoring them. If it shouldn't be an option (sometimes people get annoyed at "blank" issues), you can disable the link in `.github/ISSUE_TEMPLATE/config.yml` for the future.

### PR DESCRIPTION
**Pull request by lishaduck**
## Type

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Upgrade Shiki, which required upgrading the unified collective, which required switching to contentlayer2.

## Related

- Closes #710

### CODE REVIEW

**Comment by lishaduck** [comment]
It still uses the classic renderer, but otherwise it works now.

**Comment by IMax153** [comment]
@lishaduck - thank you very much for all your work! I'll take a closer look tomorrow. Also cc'ing @gcanti for another set of 👀 validating the Shiki visuals.

**Comment by lishaduck** [comment]
> @lishaduck - thank you very much for all your work! I'll take a closer look tomorrow.

You're welcome! And honestly, thanks! I'd been wanting to do some more investigation into Shiki, and this was the perfect excuse 🙃

**Comment by IMax153** [comment]
I looked through a bunch of the documentation and from my perspective this PR looks good. I'll wait for @gcanti to have a chance to review though.

**Review by IMax153 — APPROVED** [review]

**Comment by lishaduck** [comment]
Oh yeah, and I didn't see changesets set up. Do I need to do that here?

**Comment by IMax153** [comment]
@lishaduck - no need to create a changeset - we don't version the website in that manner.

**Review by gcanti — CHANGES_REQUESTED** [review]
Looks like there are a couple of issues:
- the code block metadatas are not respected, for example here https://website-git-fork-lishaduck-shiki-once-more-effect-ts.vercel.app/docs/quickstart the code snippets should have a "Terminal" title (see https://effect.website/docs/quickstart for reference)
- the `@include` directive of twoslash is not respected, for example https://website-git-fork-lishaduck-shiki-once-more-effect-ts.vercel.app/docs/guides/error-management/expected-errors#error-tracking

**Comment by lishaduck** [comment]
> Looks like there are a couple of issues:
> 
> * the code block metadatas are not respected, for example here https://website-git-fork-lishaduck-shiki-once-more-effect-ts.vercel.app/docs/quickstart the code snippets should have a "Terminal" title (see https://effect.website/docs/quickstart for reference)

Yeah, must've reordered too much.

> * the `@include` directive of twoslash is not respected, for example https://website-git-fork-lishaduck-shiki-once-more-effect-ts.vercel.app/docs/guides/error-management/expected-errors#error-tracking

I was looking, and it's not a twoslash feature, must've been injected by something else, I guess.

**Comment by lishaduck** [comment]
I haven't forgotten about this, it's is blocked on shikijs/shiki#737 (or equivalent) getting merged.
I'll try to finish this 🔜

**Comment by lishaduck** [comment]
Ok, been looking through the docs. Here's a list of issues for my own reference.
I think we ran into these: <https://rehype-pretty.pages.dev/#meta-strings>, I think there's a conflict with <https://rehype-pretty.pages.dev/#titles>; and possibly <https://shiki.style/packages/rehype#line-highlight> / <https://rehype-pretty.pages.dev/#highlight-lines>. I also ran into timlrx/contentlayer2#35.

Also, are we OK moving to contentlayer2 given [Reimagining ContentLayer with Effect](https://youtu.be/i4lYoTV0q6U?si=SQboE1wxXd-q30I-)? Is there a contentlayer3 hanging around somewhere?

**Comment by lishaduck** [comment]
Closing as blocked on a _separate_ contentlayer upgrade.
The scope got too big, debugging rehype isn't fun.

**Pull request closed without merging**
